//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectAutoImplementedAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class ApprovedUser
    {
        [Key]
        public int AppUserId { get; set; }
        public string UserId { get; set; }
        public int ListId { get; set; }

        public virtual UserList UserList { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
